GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "The Lord of the Rings",
  "author": "J. R. R. Tolkien",
  "year": 1954,
  "pages": 1170
}

###

PUT http://localhost:3001/books/8 HTTP/1.1
Content-Type: application/json

{
  "title": "The Lord of the Rings!",
  "author": "J. R. R. Tolkien",
  "year": 1954,
  "pages": 1170
}

###

DELETE http://localhost:3001/books/8 HTTP/1.1
Content-Type: application/json



